In [43]:
%load_ext autoreload
%autoreload 2
from mst import *
import numpy as np
from sklearn.metrics import pairwise_distances

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [77]:
file_path = './data/small.csv'
g = Graph(file_path)
g.adj_mat

array([[0., 5., 0., 5.],
       [5., 0., 1., 2.],
       [0., 1., 0., 4.],
       [5., 2., 4., 0.]])

In [65]:
import heapq
heap = [(0, (0,0))]
u, (v, w) = heapq.heappop(heap)
print(u)


0


In [55]:
g.adj_mat

array([[0., 5., 0., 5.],
       [5., 0., 1., 2.],
       [0., 1., 0., 4.],
       [5., 2., 4., 0.]])

In [30]:
n = len(g.adj_mat)
visited = set()
start = 0
heap = [(0,start)]
mst = np.array([[0 for column in range(n)] for row in range(n)])
g.adj_mat.shape

(4, 4)

In [78]:
g.construct_mst()

0
4
set()
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
1
3
{0}
[[0. 5. 0. 0.]
 [5. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
0
2
3
{0, 1}
[[0. 5. 0. 0.]
 [5. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]
1
3
{0, 1, 2}
[[0. 5. 0. 0.]
 [5. 0. 1. 2.]
 [0. 1. 0. 0.]
 [0. 2. 0. 0.]]
0
1
2


In [111]:
total = 0
for i in range(g.mst.shape[0]):
    for j in range(i+1):
        total += g.mst[i, j]

In [73]:
g.construct_mst

<bound method Graph.construct_mst of <mst.graph.Graph object at 0x7fa315907fa0>>

In [90]:
len(np.nonzero(g.mst)[1])/2

3.0

In [112]:
total

16.0

In [92]:
np.allclose(g.mst, g.mst.T, rtol=1e-05, atol=1e-08)

True

In [93]:
    adj_matrix = np.array([
        [0, 2, 0, 6, 0],
        [2, 0, 3, 8, 5],
        [0, 3, 0, 0, 7],
        [6, 8, 0, 0, 9],
        [0, 5, 7, 9, 0]
    ])
    g = Graph(adj_matrix)
    g.construct_mst()

In [95]:
len(np.nonzero(g.mst)[1])/2

4.0

In [99]:
g.mst[1].shape

(5,)

In [102]:
count = 0
for i in range(len(g.mst)):
    if g.mst[i] is not np.zeros(len(g.adj_mat)):
        count += 1

In [103]:
count

5

In [114]:
import heapq
import numpy as np

def prim(adj_matrix, start):
    n = len(adj_matrix)
    dist = [float('inf') for _ in range(n)]
    dist[start] = 0
    heap = [(0, start)]
    mst = np.zeros((n, n), dtype=int)
    cost = 0

    while heap:
        u_dist, u = heapq.heappop(heap)
        if u_dist > dist[u]:
            continue
        for v, v_dist in enumerate(adj_matrix[u]):
            if v_dist < dist[v]:
                dist[v] = v_dist
                heapq.heappush(heap, (v_dist, v))
                mst[u][v] = mst[v][u] = 1
                cost += adj_matrix[u][v]

    return mst,cost

# example usage
adj_matrix = np.array([
    [0, 2, 0, 6, 0],
    [2, 0, 3, 8, 5],
    [0, 3, 0, 0, 7],
    [6, 8, 0, 0, 9],
    [0, 5, 7, 9, 0]
])
mst,cost = prim(adj_matrix, 0)
print(mst)

[[0 1 1 1 1]
 [1 1 0 0 0]
 [1 0 0 1 0]
 [1 0 1 0 0]
 [1 0 0 0 0]]


In [116]:
cost

8

In [113]:
2 + 6 + 2 +6 

16

In [123]:
def is_connected(adj_matrix):
    visited = [False for i in range(len(adj_matrix))]
    queue = []

    start = 0  # arbitrary starting node
    queue.append(start)
    visited[start] = True

    while queue:
        node = queue.pop(0)
        for i, connected in enumerate(adj_matrix[node]):
            if connected and not visited[i]:
                print(connected)
                queue.append(i)
                visited[i] = True

    return all(visited)

In [124]:
is_connected(adj_matrix)

2
6
3
5


True

In [128]:
for i, connected in enumerate(adj_matrix[1]):
    if connected:
        print(i, connected)

0 2
2 3
3 8
4 5
